lint:
  files_unchanged:
    - .gitattributes
    - .github/CONTRIBUTING.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/linting_comment.yml
    - .markdownlint.yml
    - assets/email_template.html
    - assets/email_template.txt
    - lib/NfcoreSchema.groovy
    - lib/NfcoreTemplate.groovy
    - assets/multiqc_config.yaml
  files_exist:
    - .github/ISSUE_TEMPLATE/bug_report.md
    - .github/ISSUE_TEMPLATE/feature_request.md
    - bin/scrape_software_versions.py
    - modules/local/get_software_versions.nf
update:
  nf-core/modules:
    rseqc/bamstat: "9d0cad583b9a71a6509b754fdf589cbfbed08961"
    rseqc/inferexperiment: "9d0cad583b9a71a6509b754fdf589cbfbed08961"
    rseqc/innerdistance: "9d0cad583b9a71a6509b754fdf589cbfbed08961"
    rseqc/junctionannotation: "9d0cad583b9a71a6509b754fdf589cbfbed08961"
    rseqc/junctionsaturation: "9d0cad583b9a71a6509b754fdf589cbfbed08961"
    rseqc/readdistribution: "9d0cad583b9a71a6509b754fdf589cbfbed08961"
    rseqc/readduplication: "9d0cad583b9a71a6509b754fdf589cbfbed08961"
actions_ci: False
