# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-rnaseq-1.4.3dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## modules/local/process/sample_correlation.nf
  - conda-forge::r-base=4.0.2
  - conda-forge::r-data.table=1.12.8
  - conda-forge::r-gplots=3.0.4
  - bioconda::bioconductor-edger=3.30.0

  ### modules/local/process/rsem_calculateexpression.nf
  - bioconda::star=2.6.1d ## Don't upgrade me - 2.7X indices incompatible with iGenomes.
  - bioconda::rsem=1.3.3

